name: Reusable Workflow user
env:
  JF_ARTIFACTORY_1: ${{ secrets.artifactory_token_1 }}
  IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
  IBM_CLOUD_CF_API: ${{ secrets.IBM_CLOUD_CF_API }}
  IBM_CLOUD_CF_ORG: ${{ secrets.IBM_CLOUD_CF_ORG }}
  IBM_CLOUD_CF_SPACE: ${{ secrets.IBM_CLOUD_CF_SPACE }}
on:
  workflow_dispatch
jobs:
  do-it:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world-Looking Good11!

  build-called:
    uses: ./.github/workflows/build.yaml
    with:
      JF_ARTIFACTORY_1: ${{ secrets.artifactory_token_1 }}
  deploy-called:
    uses: ./.github/workflows/deploy.yaml
    with:
      JF_ARTIFACTORY_1: ${{ secrets.artifactory_token_1 }}
      IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
      IBM_CLOUD_CF_API: ${{ secrets.IBM_CLOUD_CF_API }}
      IBM_CLOUD_CF_ORG: ${{ secrets.IBM_CLOUD_CF_ORG }}
      IBM_CLOUD_CF_SPACE: ${{ secrets.IBM_CLOUD_CF_SPACE }}
    needs: build-called
